/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsNewRouteImport } from './routes/playlists.new'
import { Route as PlaylistsSlugRouteImport } from './routes/playlists.$slug'
import { Route as PlaylistsSlugEditRouteImport } from './routes/playlists.$slug.edit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNewRoute = PlaylistsNewRouteImport.update({
  id: '/playlists/new',
  path: '/playlists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsSlugRoute = PlaylistsSlugRouteImport.update({
  id: '/playlists/$slug',
  path: '/playlists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsSlugEditRoute = PlaylistsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PlaylistsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/upload': typeof UploadRoute
  '/playlists/$slug': typeof PlaylistsSlugRouteWithChildren
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/playlists/$slug/edit': typeof PlaylistsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/upload': typeof UploadRoute
  '/playlists/$slug': typeof PlaylistsSlugRouteWithChildren
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/playlists/$slug/edit': typeof PlaylistsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/requests': typeof RequestsRoute
  '/upload': typeof UploadRoute
  '/playlists/$slug': typeof PlaylistsSlugRouteWithChildren
  '/playlists/new': typeof PlaylistsNewRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/playlists/$slug/edit': typeof PlaylistsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/request'
    | '/requests'
    | '/upload'
    | '/playlists/$slug'
    | '/playlists/new'
    | '/playlists/'
    | '/playlists/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/request'
    | '/requests'
    | '/upload'
    | '/playlists/$slug'
    | '/playlists/new'
    | '/playlists'
    | '/playlists/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/request'
    | '/requests'
    | '/upload'
    | '/playlists/$slug'
    | '/playlists/new'
    | '/playlists/'
    | '/playlists/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RequestRoute: typeof RequestRoute
  RequestsRoute: typeof RequestsRoute
  UploadRoute: typeof UploadRoute
  PlaylistsSlugRoute: typeof PlaylistsSlugRouteWithChildren
  PlaylistsNewRoute: typeof PlaylistsNewRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/new': {
      id: '/playlists/new'
      path: '/playlists/new'
      fullPath: '/playlists/new'
      preLoaderRoute: typeof PlaylistsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$slug': {
      id: '/playlists/$slug'
      path: '/playlists/$slug'
      fullPath: '/playlists/$slug'
      preLoaderRoute: typeof PlaylistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$slug/edit': {
      id: '/playlists/$slug/edit'
      path: '/edit'
      fullPath: '/playlists/$slug/edit'
      preLoaderRoute: typeof PlaylistsSlugEditRouteImport
      parentRoute: typeof PlaylistsSlugRoute
    }
  }
}

interface PlaylistsSlugRouteChildren {
  PlaylistsSlugEditRoute: typeof PlaylistsSlugEditRoute
}

const PlaylistsSlugRouteChildren: PlaylistsSlugRouteChildren = {
  PlaylistsSlugEditRoute: PlaylistsSlugEditRoute,
}

const PlaylistsSlugRouteWithChildren = PlaylistsSlugRoute._addFileChildren(
  PlaylistsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RequestRoute: RequestRoute,
  RequestsRoute: RequestsRoute,
  UploadRoute: UploadRoute,
  PlaylistsSlugRoute: PlaylistsSlugRouteWithChildren,
  PlaylistsNewRoute: PlaylistsNewRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
